#!/bin/bash

# Linux From Scratch (LFS) Sources Directory Setup
#
# VERSION (LFS):
#   12.2
#
# VERSION (SCRIPT):
#   1.0.0.1
#
# DATE LAST EDITED:
#   03/04/2025
#
# DATE CREATED:
#   03/03/2025
#
# AUTHOR:
#   TerryJohn Anscombe
#
# USAGE:
#   sources-setup.sh [options] ARG1
#
# OPTIONS:
#   -o [file], --output=[file]      Set log file
#   -h, --help                      Display this help
#   -v, --version                   Display versions
#
# DESCRIPTION
#   Script to download needed scripts and files to build LFS builder
#
# =======================
# == SCRIPT NOT TESTED ==
# =======================

# Directorys
LFS="/mnt/lfs"
sources_directory=""$LFS"/sources"
wget_list_link="https://www.linuxfromscratch.org/lfs/downloads/stable/wget-list"
md5sums_link="https://www.linuxfromscratch.org/lfs/downloads/stable/md5sums"

# Check for sudo
#current_user="whoami"
#groups "$current_user" | grep -o 'sudo'
groups "#(id -un)" | grep -q ' sudo ' && echo "In sudo group" || echo "Not in sudo group"

# == Chapter 3. Packages and Patches ==
# == 3.1. Introduction
# This chapter includes a list of packages that need to be downloaded in order to build a
# basic Linux system. The listed version numbers correspond of the software that are
# known to work, and this script is based on their use. We highly recommend against
# using different versions, because the build commands for one version may not work with
# a different version, unless the different version is specified by an LFS erratum or
# security advisory. The newest package versions may also have problems that require
# work-arounds. These work-arounds will be developed and stabilized in the development
# version of the book.

# For some packages, the release tarball and the (Git or SVN) repositiory snapshot tarball
# for that release may be published with similar or even identical file names. But the
# release tarball may contain some files which are essential despite not stored in the
# repository (for examoke, a 'configure' scropt generated by 'autoconf'), in addition to
# the contents of the corresponding repository snapshot. The script uses release tarballs
# whenever possible. Using a repositiory snapshot instead of a release tarball
# specified by the script will cause problems.

# Download locations may not always be accessible. If a download location has changed
# since this script was published, Google (https://www.google.com/) provides a useful
# search engine for most packages. If this search is unsuccessful, try one of the
# alternative means of downloading at:
#    "https://www.linuxfromscratch.org/lfs/mirrors.html#files"

# Downloaded pavkages and patches will need to be stored somewhere that is conveniently
# available throughout the entire build. A working directory is also required to unpack
# the sources and build them. '$LFS/sources' can be used both as the place to store the
# tarballs and patches and as a working directory. By using this directory, the
# required elements will be located on the LFS partition and will be available during
# all stages of the building process.

# Create the directory, execute the following command, as user 'root', before starting the
# download session:
mkdir            \
    --verbose    \
    "$sources_directory"

# Make this directory writable and sticky. "Sticky" means that even if multiple users have
# write permission on a directory, only the owner of a file can delete the file within a
# sticky directory. The following command will enable the write and sticky modes:
chmod           \
    --verbose   \
    a+wt        \
    "$sources_directory"

# There are seveeral ways to obtain all the necessary packages and patches to build LFS:
# - The files can be downloaded individually as described in the next two sections.
# - For stable versions of the book, a tarball of all the needed files can be downloaded
#   from one of the mirror sites listed at:
#       "https://www.linuxfromsratch.org/mirrors.html#files"
# - The files can be downloaded using wget and a wget-list as described below.

# To download all of the packages and patches by using wget-list as an input to the wget
# command, use:
wget "$wget_list_link"
wget "$md5sums_link"

wget                            \
    --input-file="wget-list"    \
    --continue                  \
    --directory-prefix="$sources_directory"

# Additionally, starting with LFS, there is a separate file, md5sums, which can be used to
# verify that all the correct packages are available before proceeding. Pkace that file in
# $LFS/sources and run:
pushd "$sources_directory"
    md5sums        \
        --check    \
        md5sums
popd
# This check can be used after retrieving the needed files with any of the methods above.

# If the packages and patches are downloaded as a non-root user, these files will be owned
# by the user. The file system records the owner by its UID, and the UID of a normal user
# in the host distro is not assigned in LFS. So the files will be left owned by an unnamed
# UID in the final LFS system. If you won't assign the same UID for your user in the LFS
# system, change the owners of these files to 'root' now to avoid this issue:
chown            \
    --verbose    \
    root:root    \
    ""$sources_directory"/*"

# == 3.2. All Packages
# = NOTES =
#    Read the security advisories before downloading packages to figure out if a newer
#    version of any package should be used to avoid security vulnerabilities.

#    The upstream sources may remove old releases, especially when those releases contain
#    a security vulnerability. If one URL below is not reachable, you should read the
#    security advisories first to figure out if a newer version (with the vulnerability
#    fixed) should be used. If not, try to download the removed package from a mirror.
#    Although it's possible to download an old release from a mirror even if this
#    release has been removed because of a vulnerability, it's not goof idea to use a
#    release known to be vulnerable when building your system.

# Download or otherwise obtain the following packages:
# - Acl (2.3.2) - 363 KB:
#    Home page: https://savannah.nongnu.org/projects/acl
#    Download: https://download.savannah.gnu.org/releases/acl/acl-2.3.2.tar.xz
#    MD5 sum: 590765dee95907dbc3c856f7255bd669
# - Attr (2.5.2) - 484 KB:
#    Home page: https://savannah.nongnu.org/projects/attr
#    Download: https://download.savannah.gnu.org/releases/attr/attr-2.5.2.tar.gz
#    MD5 sum: 227043ec2f6ca03c0948df5517f9c927
# - Autoconf (2.72) - 1,360 KB:
#    Home page: https://www.gnu.org/software/autoconf/
#    Download: https://ftp.gnu.org/gnu/autoconf/autoconf-2.72.tar.xz
#    MD5 sum: 1be79f7106ab6767f18391c5e22be701
# - Automake (1.17) - 1,614 KB:
#    Home page: https://www.gnu.org/software/automake/
#    Download: https://ftp.gnu.org/gnu/automake/automake-1.17.tar.xz
#    MD5 sum: 7ab3a02318fee6f5bd42adfc369abf10
# - Bash (5.2.37) - 10,868 KB:
#    Home page: https://www.gnu.org/software/bash/
#    Download: https://ftp.gnu.org/gnu/bash/bash-5.2.37.tar.gz
#    MD5 sum: 9c28f21ff65de72ca329c1779684a972
# - Bc (7.0.3) - 464 KB:
#    Home page: https://git.gavinhoward.com/gavin/bc
#    Download: https://github.com/gavinhoward/bc/releases/download/7.0.3/bc-7.0.3.tar.xz
#    MD5 sum: ad4db5a0eb4fdbb3f6813be4b6b3da74
# - Binutils (2.44) - 26,647 KB:
#    Home page: https://www.gnu.org/software/binutils/
#    Download: https://sourceware.org/pub/binutils/releases/binutils-2.44.tar.xz
#    MD5 sum: 49912ce774666a30806141f106124294
# - Bison (3.8.2) - 2,752 KB:
#    Home page: https://www.gnu.org/software/bison/
#    Download: https://ftp.gnu.org/gnu/bison/bison-3.8.2.tar.xz
#    MD5 sum: c28f119f405a2304ff0a7ccdcc629713
# - Bzip2 (1.0.8) - 792 KB:
#    Download: https://www.sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz
#    MD5 sum: 67e051268d0c475ea773822f7500d0e5
# - Check (0.15.2) - 760 KB:
#    Home page: https://libcheck.github.io/check
#    Download: https://github.com/libcheck/check/releases/download/0.15.2/check-0.15.2.tar.gz
#    MD5 sum: 50fcafcecde5a380415b12e9c574e0b2
# - Coreutils (9.6) - 5,991 KB:
#    Home page: https://www.gnu.org/software/coreutils/
#    Download: https://ftp.gnu.org/gnu/coreutils/coreutils-9.6.tar.xz
#    MD5 sum: 0ed6cc983fe02973bc98803155cc1733
# - DejaGNU (1.6.3) - 608 KB:
#    Home page: https://www.gnu.org/software/dejagnu/
#    Download: https://ftp.gnu.org/gnu/dejagnu/dejagnu-1.6.3.tar.gz
#    MD5 sum: 68c5208c58236eba447d7d6d1326b821
# - Diffutils (3.11) - 1,881 KB:
#    Home page: https://www.gnu.org/software/diffutils/
#    Download: https://ftp.gnu.org/gnu/diffutils/diffutils-3.11.tar.xz
#    MD5 sum: 75ab2bb7b5ac0e3e10cece85bd1780c2
# - E2fsprogs (1.47.2) - 9,763 KB:
#    Home page: https://e2fsprogs.sourceforge.net/
#    Download: https://downloads.sourceforge.net/project/e2fsprogs/e2fsprogs/v1.47.2/e2fsprogs-1.47.2.tar.gz
#    MD5 sum: 752e5a3ce19aea060d8a203f2fae9baa
# - Elfutils (0.192) - 11,635 KB:
#    Home page: https://sourceware.org/elfutils/
#    Download: https://sourceware.org/ftp/elfutils/0.192/elfutils-0.192.tar.bz2
#    MD5 sum: a6bb1efc147302cfc15b5c2b827f186a
# - Expat (2.6.4) - 476 KB:
#    Home page: https://libexpat.github.io/
#    Download: https://prdownloads.sourceforge.net/expat/expat-2.6.4.tar.xz
#    MD5 sum: 101fe3e320a2800f36af8cf4045b45c7
# - Expect (5.45.4) - 618 KB:
#    Home page: https://core.tcl.tk/expect/
#    Download: https://prdownloads.sourceforge.net/expect/expect5.45.4.tar.gz
#    MD5 sum: 00fce8de158422f5ccd2666512329bd2
# - File (5.46) - 1,283 KB:
#    Home page: https://www.darwinsys.com/file/
#    Download: https://astron.com/pub/file/file-5.46.tar.gz
#    MD5 sum: 459da2d4b534801e2e2861611d823864
# - Findutils (4.10.0) - 2,189 KB:
#    Home page: https://www.gnu.org/software/findutils/
#    Download: https://ftp.gnu.org/gnu/findutils/findutils-4.10.0.tar.xz
#    MD5 sum: 870cfd71c07d37ebe56f9f4aaf4ad872
# - Flex (2.6.4) - 1,386 KB:
#    Home page: https://github.com/westes/flex
#    Download: https://github.com/westes/flex/releases/download/v2.6.4/flex-2.6.4.tar.gz
#    MD5 sum: 2882e3179748cc9f9c23ec593d6adc8d
# - Flit-core (3.11.0) - 51 KB:
#    Home page: https://pypi.org/project/flit-core/
#    Download: https://pypi.org/packages/source/f/flit-core/flit_core-3.11.0.tar.gz
#    MD5 sum: 6d677b1acef1769c4c7156c7508e0dbd
# - Gawk (5.3.1) - 3,428 KB:
#    Home page: https://www.gnu.org/software/gawk/
#    Download: https://ftp.gnu.org/gnu/gawk/gawk-5.3.1.tar.xz
#    MD5 sum: 4e9292a06b43694500e0620851762eec
# - GCC (14.2.0) - 90,144 KB:
#    Home page: https://gcc.gnu.org/
#    Download: https://ftp.gnu.org/gnu/gcc/gcc-14.2.0/gcc-14.2.0.tar.xz
#    MD5 sum: 2268420ba02dc01821960e274711bde0
# - GDBM (1.24) - 1,168 KB:
#    Home page: https://www.gnu.org/software/gdbm/
#    Download: https://ftp.gnu.org/gnu/gdbm/gdbm-1.24.tar.gz
#    MD5 sum: c780815649e52317be48331c1773e987
# - Gettext (0.24) - 8,120 KB:
#    Home page: https://www.gnu.org/software/gettext/
#    Download: https://ftp.gnu.org/gnu/gettext/gettext-0.24.tar.xz
#    MD5 sum: 87aea3013802a3c60fa3feb5c7164069
# - Glibc (2.41) - 18,892 KB:
#    Home page: https://www.gnu.org/software/libc/
#    Download: https://ftp.gnu.org/gnu/glibc/glibc-2.41.tar.xz
#    MD5 sum: 19862601af60f73ac69e067d3e9267d4

# == Note ==
# The Glibc developers maintain a 'Git branch' containing patches considered worthy for
# Glibc-2.41 but unfortunately developed after Glibc-2.41 release. The LFS editors will
# issue a security advisory if any security fix is added into the branch, but no actions
# will be taken for other newly added patches. You may review the patches yourself and
# incorporate some patches if you consider them important.

# - GMP (6.3.0) - 2,046 KB:
#    Home page: https://www.gnu.org/software/gmp/
#    Download: https://ftp.gnu.org/gnu/gmp/gmp-6.3.0.tar.xz
#    MD5 sum: 956dc04e864001a9c22429f761f2c283
# - Gperf (3.1) - 1,188 KB:
#    Home page: https://www.gnu.org/software/gperf/
#    Download: https://ftp.gnu.org/gnu/gperf/gperf-3.1.tar.gz
#    MD5 sum: 9e251c0a618ad0824b51117d5d9db87e
# - Grep (3.11) - 1,664 KB:
#    Home page: https://www.gnu.org/software/grep/
#    Download: https://ftp.gnu.org/gnu/grep/grep-3.11.tar.xz
#    MD5 sum: 7c9bbd74492131245f7cdb291fa142c0
# - Groff (1.23.0) - 7,259 KB:
#    Home page: https://www.gnu.org/software/groff/
#    Download: https://ftp.gnu.org/gnu/groff/groff-1.23.0.tar.gz
#    MD5 sum: 5e4f40315a22bb8a158748e7d5094c7d
# - GRUB (2.12) - 6,524 KB:
#    Home page: https://www.gnu.org/software/grub/
#    Download: https://ftp.gnu.org/gnu/grub/grub-2.12.tar.xz
#    MD5 sum: 60c564b1bdc39d8e43b3aab4bc0fb140
# - Gzip (1.13) - 819 KB:
#    Home page: https://www.gnu.org/software/gzip/
#    Download: https://ftp.gnu.org/gnu/gzip/gzip-1.13.tar.xz
#    MD5 sum: d5c9fc9441288817a4a0be2da0249e29
# - Iana-Etc (20250123) - 591 KB:
#    Home page: https://www.iana.org/protocols
#    Download: https://github.com/Mic92/iana-etc/releases/download/20250123/iana-etc-20250123.tar.gz
#    MD5 sum: f8a0ebdc19a5004cf42d8bdcf614fa5d
# - Inetutils (2.6) - 1,724 KB:
#    Home page: https://www.gnu.org/software/inetutils/
#    Download: https://ftp.gnu.org/gnu/inetutils/inetutils-2.6.tar.xz
#    MD5 sum: 401d7d07682a193960bcdecafd03de94
# - Intltool (0.51.0) - 159 KB:
#    Home page: https://freedesktop.org/wiki/Software/intltool
#    Download: https://launchpad.net/intltool/trunk/0.51.0/+download/intltool-0.51.0.tar.gz
#    MD5 sum: 12e517cac2b57a0121cda351570f1e63
# - IPRoute2 (6.13.0) - 906 KB:
#    Home page: https://www.kernel.org/pub/linux/utils/net/iproute2/
#    Download: https://www.kernel.org/pub/linux/utils/net/iproute2/iproute2-6.13.0.tar.xz
#    MD5 sum: 1603d25120d03feeaba9b360d03ffaec
# - Jinja2 (3.1.5) - 239 KB:
#    Home page: https://jinja.palletsprojects.com/en/3.1.x/
#    Download: https://pypi.org/packages/source/J/Jinja2/jinja2-3.1.5.tar.gz
#    MD5 sum: 083d64f070f6f1b5f75971ae60240785
# - Kbd (2.7.1) - 1,438 KB:
#    Home page: https://kbd-project.org/
#    Download: https://www.kernel.org/pub/linux/utils/kbd/kbd-2.7.1.tar.xz
#    MD5 sum: f15673d9f748e58f82fa50cff0d0fd20
# - Kmod (34) - 331 KB:
#    Home page: https://github.com/kmod-project/kmod
#    Download: https://www.kernel.org/pub/linux/utils/kernel/kmod/kmod-34.tar.xz
#    MD5 sum: 3e6c5c9ad9c7367ab9c3cc4f08dfde62
# - Less (668) - 635 KB:
#    Home page: https://www.greenwoodsoftware.com/less/
#    Download: https://www.greenwoodsoftware.com/less/less-668.tar.gz
#    MD5 sum: d72760386c5f80702890340d2f66c302
# - LFS-Bootscripts (20240825) - 33 KB:
#    Download: https://www.linuxfromscratch.org/lfs/downloads/12.3/lfs-bootscripts-20240825.tar.xz
#    MD5 sum: 7b078c594a77e0f9cd53a0027471c3bc
# - Libcap (2.73) - 191 KB:
#    Home page: https://sites.google.com/site/fullycapable/
#    Download: https://www.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-2.73.tar.xz
#    MD5 sum: 0e186df9de9b1e925593a96684fe2e32
# - Libffi (3.4.7) - 1,362 KB:
#    Home page: https://sourceware.org/libffi/
#    Download: https://github.com/libffi/libffi/releases/download/v3.4.7/libffi-3.4.7.tar.gz
#    MD5 sum: 696a1d483a1174ce8a477575546a5284
# - Libpipeline (1.5.8) - 1046 KB:
#    Home page: https://libpipeline.nongnu.org/
#    Download: https://download.savannah.gnu.org/releases/libpipeline/libpipeline-1.5.8.tar.gz
#    MD5 sum: 17ac6969b2015386bcb5d278a08a40b5
# - Libtool (2.5.4) - 1,033 KB:
#    Home page: https://www.gnu.org/software/libtool/
#    Download: https://ftp.gnu.org/gnu/libtool/libtool-2.5.4.tar.xz
#    MD5 sum: 22e0a29df8af5fdde276ea3a7d351d30
# - Libxcrypt (4.4.38) - 612 KB:
#    Home page: https://github.com/besser82/libxcrypt/
#    Download: https://github.com/besser82/libxcrypt/releases/download/v4.4.38/libxcrypt-4.4.38.tar.xz
#    MD5 sum: 1796a5d20098e9dd9e3f576803c83000
# - Linux (6.13.4) - 145,015 KB:
#    Home page: https://www.kernel.org/
#    Download: https://www.kernel.org/pub/linux/kernel/v6.x/linux-6.13.4.tar.xz
#    MD5 sum: 13b9e6c29105a34db4647190a43d1810

# == Note ==
# The Linux kernel is updated quite frequently, many times due to discoveries of
# security vulnerabilities. The latest available stable kernel version may be used,
# unless the errata page says otherwise.
# For users with limited speed or expensive bandwidth who wish to update the Linux
# kernel, a baseline version of the package and patches can be downloaded separately.
# This may save some time or cost for a subsequent patch level upgrade within a minor
# release.

# - Lz4 (1.10.0) - 379 KB:
#    Home page: https://lz4.org/
#    Download: https://github.com/lz4/lz4/releases/download/v1.10.0/lz4-1.10.0.tar.gz
#    MD5 sum: dead9f5f1966d9ae56e1e32761e4e675
# - M4 (1.4.19) - 1,617 KB:
#    Home page: https://www.gnu.org/software/m4/
#    Download: https://ftp.gnu.org/gnu/m4/m4-1.4.19.tar.xz
#    MD5 sum: 0d90823e1426f1da2fd872df0311298d
# - Make (4.4.1) - 2,300 KB:
#    Home page: https://www.gnu.org/software/make/
#    Download: https://ftp.gnu.org/gnu/make/make-4.4.1.tar.gz
#    MD5 sum: c8469a3713cbbe04d955d4ae4be23eeb
# - Man-DB (2.13.0) - 2,023 KB:
#    Home page: https://www.nongnu.org/man-db/
#    Download: https://download.savannah.gnu.org/releases/man-db/man-db-2.13.0.tar.xz
#    MD5 sum: 97ab5f9f32914eef2062d867381d8cee
# - Man-pages (6.12) - 1,838 KB:
#    Home page: https://www.kernel.org/doc/man-pages/
#    Download: https://www.kernel.org/pub/linux/docs/man-pages/man-pages-6.12.tar.xz
#    MD5 sum: 44de430a598605eaba3e36dd43f24298
# - MarkupSafe (3.0.2) - 21 KB:
#    Home page: https://palletsprojects.com/p/markupsafe/
#    Download: https://pypi.org/packages/source/M/MarkupSafe/markupsafe-3.0.2.tar.gz
#    MD5 sum: cb0071711b573b155cc8f86e1de72167
# - Meson (1.7.0) - 2,241 KB:
#    Home page: https://mesonbuild.com
#    Download: https://github.com/mesonbuild/meson/releases/download/1.7.0/meson-1.7.0.tar.gz
#    MD5 sum: c20f3e5ebbb007352d22f4fd6ceb925c
# - MPC (1.3.1) - 756 KB:
#    Home page: https://www.multiprecision.org/
#    Download: https://ftp.gnu.org/gnu/mpc/mpc-1.3.1.tar.gz
#    MD5 sum: 5c9bc658c9fd0f940e8e3e0f09530c62
# - MPFR (4.2.1) - 1,459 KB:
#    Home page: https://www.mpfr.org/
#    Download: https://ftp.gnu.org/gnu/mpfr/mpfr-4.2.1.tar.xz
#    MD5 sum: 523c50c6318dde6f9dc523bc0244690a
# - Ncurses (6.5) - 2,156 KB:
#    Home page: https://www.gnu.org/software/ncurses/
#    Download: https://invisible-mirror.net/archives/ncurses/ncurses-6.5.tar.gz
#    MD5 sum: ac2d2629296f04c8537ca706b6977687
# - Ninja (1.12.1) - 235 KB:
#    Home page: https://ninja-build.org/
#    Download: https://github.com/ninja-build/ninja/archive/v1.12.1/ninja-1.12.1.tar.gz
#    MD5 sum: 6288992b05e593a391599692e2f7e490
# - OpenSSL (3.4.1) - 17,917 KB:
#    Home page: https://www.openssl-library.org/
#    Download: https://github.com/openssl/openssl/releases/download/openssl-3.4.1/openssl-3.4.1.tar.gz
#    MD5 sum: fb7a747ac6793a7ad7118eaba45db379
# - Patch (2.7.6) - 766 KB:
#    Home page: https://savannah.gnu.org/projects/patch/
#    Download: https://ftp.gnu.org/gnu/patch/patch-2.7.6.tar.xz
#    MD5 sum: 78ad9937e4caadcba1526ef1853730d5
# - Perl (5.40.1) - 13,605 KB:
#    Home page: https://www.perl.org/
#    Download: https://www.cpan.org/src/5.0/perl-5.40.1.tar.xz
#    MD5 sum: bab3547a5cdf2302ee0396419d74a42e
# - Pkgconf (2.3.0) - 309 KB:
#    Home page: https://github.com/pkgconf/pkgconf
#    Download: https://distfiles.ariadne.space/pkgconf/pkgconf-2.3.0.tar.xz
#    MD5 sum: 833363e77b5bed0131c7bc4cc6f7747b
# - Procps (4.0.5) - 1,483 KB:
#    Home page: https://gitlab.com/procps-ng/procps/
#    Download: https://sourceforge.net/projects/procps-ng/files/Production/procps-ng-4.0.5.tar.xz
#    MD5 sum: 90803e64f51f192f3325d25c3335d057
# - Psmisc (23.7) - 423 KB:
#    Home page: https://gitlab.com/psmisc/psmisc
#    Download: https://sourceforge.net/projects/psmisc/files/psmisc/psmisc-23.7.tar.xz
#    MD5 sum: 53eae841735189a896d614cba440eb10
# - Python (3.13.2) - 22,091 KB:
#    Home page: https://www.python.org/
#    Download: https://www.python.org/ftp/python/3.13.2/Python-3.13.2.tar.xz
#    MD5 sum: 4c2d9202ab4db02c9d0999b14655dfe5
# - Python Documentation (3.13.2) - 10,102 KB:
#    Download: https://www.python.org/ftp/python/doc/3.13.2/python-3.13.2-docs-html.tar.bz2
#    MD5 sum: d6aede88f480a018d26b3206f21654ae
# - Readline (8.2.13) - 2,974 KB:
#    Home page: https://tiswww.case.edu/php/chet/readline/rltop.html
#    Download: https://ftp.gnu.org/gnu/readline/readline-8.2.13.tar.gz
#    MD5 sum: 05080bf3801e6874bb115cd6700b708f
# - Sed (4.9) - 1,365 KB:
#    Home page: https://www.gnu.org/software/sed/
#    Download: https://ftp.gnu.org/gnu/sed/sed-4.9.tar.xz
#    MD5 sum: 6aac9b2dbafcd5b7a67a8a9bcb8036c3
# - Setuptools (75.8.1) - 1,313 KB:
#    Home page: https://pypi.org/project/setuptools/
#    Download: https://pypi.org/packages/source/s/setuptools/setuptools-75.8.1.tar.gz
#    MD5 sum: 7dc3d3f529b76b10e35326e25c676b30
# - Shadow (4.17.3) - 2,274 KB:
#    Home page: https://github.com/shadow-maint/shadow/
#    Download: https://github.com/shadow-maint/shadow/releases/download/4.17.3/shadow-4.17.3.tar.xz
#    MD5 sum: 0da190e53ecee76237e4c8f3f39531ed
# - Sysklogd (2.7.0) - 465 KB:
#    Home page: https://www.infodrom.org/projects/sysklogd/
#    Download: https://github.com/troglobit/sysklogd/releases/download/v2.7.0/sysklogd-2.7.0.tar.gz
#    MD5 sum: 611c0fa5c138eb7a532f3c13bdf11ebc
# - Systemd (257.3) - 15,847 KB:
#    Home page: https://www.freedesktop.org/wiki/Software/systemd/
#    Download: https://github.com/systemd/systemd/archive/v257.3/systemd-257.3.tar.gz
#    MD5 sum: 8e4fc90c7aead651fa5c50bd1b34abc2
# - Systemd Man Pages (257.3) - 733 KB:
#    Home page: https://www.freedesktop.org/wiki/Software/systemd/
#    Download: https://anduin.linuxfromscratch.org/LFS/systemd-man-pages-257.3.tar.xz
#    MD5 sum: 9b77c3b066723d490cb10aed4fb05696

# == Note ==
# The Linux From Scratch team generates its own tarball of the man pages using the
# systemd source. This is done in order to avoid unnecessary dependencies.

# - SysVinit (3.14) - 236 KB:
#    Home page: https://savannah.nongnu.org/projects/sysvinit
#    Download: https://github.com/slicer69/sysvinit/releases/download/3.14/sysvinit-3.14.tar.xz
#    MD5 sum: bc6890b975d19dc9db42d0c7364dd092
# - Tar (1.35) - 2,263 KB:
#    Home page: https://www.gnu.org/software/tar/
#    Download: https://ftp.gnu.org/gnu/tar/tar-1.35.tar.xz
#    MD5 sum: a2d8042658cfd8ea939e6d911eaf4152
# - Tcl (8.6.16) - 11,406 KB:
#    Home page: https://tcl.sourceforge.net/
#    Download: https://downloads.sourceforge.net/tcl/tcl8.6.16-src.tar.gz
#    MD5 sum: eaef5d0a27239fb840f04af8ec608242
# - Tcl Documentation (8.6.16) - 1,169 KB:
#    Download: https://downloads.sourceforge.net/tcl/tcl8.6.16-html.tar.gz
#    MD5 sum: 750c221bcb6f8737a6791c1fbe98b684
# - Texinfo (7.2) - 6,259 KB:
#    Home page: https://www.gnu.org/software/texinfo/
#    Download: https://ftp.gnu.org/gnu/texinfo/texinfo-7.2.tar.xz
#    MD5 sum: 11939a7624572814912a18e76c8d8972
# - Time Zone Data (2025a) - 453 KB:
#    Home page: https://www.iana.org/time-zones
#    Download: https://www.iana.org/time-zones/repository/releases/tzdata2025a.tar.gz
#    MD5 sum: 404229390c06b7440f5e48d12c1a3251
# - Udev-lfs Tarball (udev-lfs-20230818) - 10 KB:
#    Download: https://anduin.linuxfromscratch.org/LFS/udev-lfs-20230818.tar.xz
#    MD5 sum: acd4360d8a5c3ef320b9db88d275dae6
# - Util-linux (2.40.4) - 8,641 KB:
#    Home page: https://git.kernel.org/pub/scm/utils/util-linux/util-linux.git/
#    Download: https://www.kernel.org/pub/linux/utils/util-linux/v2.40/util-linux-2.40.4.tar.xz
#    MD5 sum: f9cbb1c8315d8ccbeb0ec36d10350304
# - Vim (9.1.1166) - 18,077 KB:
#    Home page: https://www.vim.org
#    Download: https://github.com/vim/vim/archive/v9.1.1166/vim-9.1.1166.tar.gz
#    MD5 sum: 718d43ce957ab7c81071793de176c2eb

# == Note ==
# The version of vim changes daily. To get the latest version, go to:
#    'https://github.com/vim/vim/tags'

# - Wheel (0.45.1) - 106 KB:
#    Home page: https://pypi.org/project/wheel/
#    Download: https://pypi.org/packages/source/w/wheel/wheel-0.45.1.tar.gz
#    MD5 sum: dddc505d0573d03576c7c6c5a4fe0641
# - XML::Parser (2.47) - 276 KB:
#    Home page: https://github.com/chorny/XML-Parser
#    Download: https://cpan.metacpan.org/authors/id/T/TO/TODDR/XML-Parser-2.47.tar.gz
#    MD5 sum: 89a8e82cfd2ad948b349c0a69c494463
# - Xz Utils (5.6.4) - 1,310 KB:
#    Home page: https://tukaani.org/xz
#    Download: https://github.com//tukaani-project/xz/releases/download/v5.6.4/xz-5.6.4.tar.xz
#    MD5 sum: 4b1cf07d45ec7eb90a01dd3c00311a3e
# - Zlib (1.3.1) - 1,478 KB:
#    Home page: https://zlib.net/
#    Download: https://zlib.net/fossils/zlib-1.3.1.tar.gz
#    MD5 sum: 9855b6d802d7fe5b7bd5b196a2271655
# - Zstd (1.5.7) - 2,378 KB:
#    Home page: https://facebook.github.io/zstd/
#    Download: https://github.com/facebook/zstd/releases/download/v1.5.7/zstd-1.5.7.tar.gz
#    MD5 sum: 780fc1896922b1bc52a4e90980cdda48

# Total size of these packages: about 527 MB

# == 3.3. Needed Patches
# In addition to the packages, several patches are also required. These patches correct
# any mistakes in the packages that should be fixed by the maintainer. The patches also
# make small modifications to make the packages easier to work with. The following
# patches will be needed to build an LFS system:
# - Bzip2 Documentation Patch - 1.6 KB:
#    Download: https://www.linuxfromscratch.org/patches/lfs/12.3/bzip2-1.0.8-install_docs-1.patch
#    MD5 sum: 6a5ac7e89b791aae556de0f745916f7f
# - Coreutils Internationalization Fixes Patch - 164 KB:
#    Download: https://www.linuxfromscratch.org/patches/lfs/12.3/coreutils-9.6-i18n-1.patch
#    MD5 sum: 6aee45dd3e05b7658971c321d92f44b7
# - Expect GCC14 Patch - 7.8 KB:
#    Download: https://www.linuxfromscratch.org/patches/lfs/12.3/expect-5.45.4-gcc14-1.patch
#    MD5 sum: 0b8b5ac411d011263ad40b0664c669f0
# - Glibc FHS Patch - 2.8 KB:
#    Download: https://www.linuxfromscratch.org/patches/lfs/12.3/glibc-2.41-fhs-1.patch
#    MD5 sum: 9a5997c3452909b1769918c759eff8a2
# - Kbd Backspace/Delete Fix Patch - 12 KB:
#    Download: https://www.linuxfromscratch.org/patches/lfs/12.3/kbd-2.7.1-backspace-1.patch
#    MD5 sum: f75cca16a38da6caa7d52151f7136895
# - SysVinit Consolidated Patch - 2.5 KB:
#    Download: https://www.linuxfromscratch.org/patches/lfs/12.3/sysvinit-3.14-consolidated-1.patch
#    MD5 sum: 3af8fd8e13cad481eeeaa48be4247445

# Total size of these patches: about 190.7 KB

# In addition to the above required patches, there exist a number of optional patches
# created by the LFS community. These optional patches solve minor problems or enable
# functionality that is not enabled by default. Feel free to peruse the patches
# database located at https://www.linuxfromscratch.org/patches/downloads/ and acquire
# any additional patches to suit your system needs.

# == Chapter 4. Final Preparations ==
# == 4.1. Introduction ==
# In this chapter, we will perform a few additional tasks to prepare for building
# temporary system. We will create a set of directories in '$LFS' (in which we will
# install the temporary tools), add an unprivileged user, and create an appropriate
# build environment for that user. We will also explain the units of time ("SBUs") we
# use to measure how long it takes to build LFS packages, and provide some
# information about package test suites.

# == 4.2. Creating a Limited Directory Layout in the LFS Filesystem
# In this section, we begin populating the LFS filesystem with the pieces that will
# constitute the final Linux system. The first step is to create a limited directory
# hierarchy, so that the programs compiled in Chapter 6 (as well as glibc and libstdc++
# in Chapter 5) can be installed in their final location. We do this so those temporary
# programs will be overwritten when the final versions are built in Chapter 8.

# Create the required directory layout by issuing the following commands as root:
mkdir            \
    --verbose    \
    --parents    \
    "$LFS"/{eetc,var} "$LFS"/usr/{bin,lib,sbin}

for i in bin lib sib; do
    ln               \
        --verbose    \
        --symbolic   \
        usr/$1 $LFS/$i
done

case $(uname -m) in
    x86_64) mkdir     \
        --verbose     \
        --parents     \
        "$LFS"/lib64 ;;
esac

# Programs in Chapter 6 will compiled with a cross-compiler (more details can be found in
# section Toolchain Technical Notes). This cross-compiler will be installed in a special
# directory, to separate it from the other programs. Still acting as root, crate that
# directory with the command:
mkdir            \
    --verbose    \
    --parents    \
    $LFS/tools

# == NOTE ==
# The LFS editors have deliberately decided not to use a /usr/lib64 directory. Several
# steps are taken to be sure the toolchain will not use it. If for any reason this directory
# appears (either because you made an error in following the instructions, or because you
# installed a binary package that created it after finishing LFS), it may break your system.
# You should always be sure this directory does not exist.

# == 4.3. Adding the LFS User ==
# When logged in as user root, making a single mistake can damage or destroy a system.
# Therefore. the packages in the next two chapters are built as an unprivileged user. You
# could use your own user name, but to make it easier to set up a clean working
# environment, we will create a new user called lfs as a member of a new group (also named
# lfs) and run commands as lfs during the installation process. As root, issue the following
# commands to add the new user:
groupadd "lfs"
useradd                 \
    --shell "/bin/bash" \
    --gid "lfs"         \
    --create-home       \
    --skel "/dev/null"  \
    "lfs"

# This is what the command line options mean:
# -s /bin/bash, --shell /bin/bash
#   This makes bash the default shell for user 'lfs'.
# -g lfs, --gid lfs
#   This option adds user lfs to group 'lfs'.
# -m, --create-home
#   This creates a home directory for 'lfs'.
# -k /dev/null, -skel /dev/null
#   This parameter prevents possible copying of files from a skeleton directory (the default
#   'is /etc/skel') by changing the input location to the special null device.
# lfs
#   This is the name of the new user.

# If you want vto log in as 'lfs' or switch to 'lfs' from a non-root user (as opposed to
# switching to user 'lfs' when logged in as root, which does not require the lfs user to have
# a password), you need to set a password for 'lfs'. Issue the following command as the 'root'
# user to set the password:
passwd lfs

# Grant 'lfs' full access to all directories under '$LFS' by making 'lfs' the owner:
chown --verbose lfs $LFS/{usr{,/*},lib,var,etc,bin,sbin,tools}
case $(uname --machine) in
    x86_64) chown --verbose lfs $LFS/lib64 ;;
esac

# == Note ==
# In some host systems, the following su command does not complete properly and suspends the
# login for the lfs user to the background. If the prompt "lfs:~$" does not appear
# imediately, entering the fg command will fix the issue.

# Next, start a shell running as user lfs. This can be done by logging in as lfs on a virtual
# console, or with the following substitute/switch user command:
#    su - lfs
echo 'Run 'su - lfs' to login to lfs user.'
# The “-” instructs su to start a login shell as opposed to a non-login shell. The difference
# between these two types of shells is described in detail in bash(1) and info bash.
